---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dragonfly
  automountServiceAccountToken: false
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  replicas: 3
  image: ghcr.io/dragonflydb/dragonfly:v1.40.1@sha256:ebf3c6c213e82fb51b4521660cca13f06f3421dc5b1ed14f2f474c50b5e29986
  imagePullPolicy: IfNotPresent
  serviceAccountName: dragonfly
  networkPolicyEnabled: false
  enableReplicationReadinessGate: true
  args:
    - --cache_mode=false
    - --maxmemory=4Gi
    - --proactor_threads=2
  aclFromSecret:
    name: dragonfly-acl
    key: acl.conf
  tlsSecretRef:
    name: dragonfly-server-tls
  resources:
    requests: { cpu: 500m, memory: 2Gi }
    limits: { cpu: "2", memory: 6Gi }
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities: { drop: [ALL] }
    readOnlyRootFilesystem: true
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile: { type: RuntimeDefault }
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          dragonfly.dragonflydb.io/name: dragonfly
  pdb:
    minAvailable: 2
  snapshot:
    cron: "0 * * * *"
    enableOnMasterOnly: true
    persistentVolumeClaimSpec:
      accessModes: [ReadWriteOnce]
      storageClassName: ceph-rbd-retain
      resources:
        requests:
          storage: 20Gi
  ownedObjectsMetadata:
    labels:
      backup.monosense.io/enabled: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-internal
  labels:
    lbipam.monosense.io/class: internal
    bgp.monosense.io/advertise: "true"
  annotations:
    lbipam.cilium.io/ips: 10.25.20.41
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  loadBalancerSourceRanges:
    - 10.25.10.101/32
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dragonfly
    dragonfly.dragonflydb.io/name: dragonfly
    dragonfly.dragonflydb.io/role: master
  ports:
    - name: dragonfly-tls
      port: 6379
      targetPort: 6379
      protocol: TCP
