---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-config
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: alertmanager-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            receiver: telegram
            group_by: [alertname, namespace, severity]
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 4h
          receivers:
            - name: telegram
              telegram_configs:
                - bot_token: '{{ .telegram_bot_token }}'
                  chat_id: {{ .telegram_chat_id }}
                  send_resolved: true
                  parse_mode: ''
                  message: |-
                    {{ "{{" }} if eq .Status "firing" {{ "}}" }}FIRING{{ "{{" }} else {{ "}}" }}RESOLVED{{ "{{" }} end {{ "}}" }}
                    alert={{ "{{" }} .CommonLabels.alertname {{ "}}" }}
                    severity={{ "{{" }} .CommonLabels.severity {{ "}}" }}
                    namespace={{ "{{" }} .CommonLabels.namespace {{ "}}" }}
  dataFrom:
    - extract:
        key: platform/kubernetes/observability/alertmanager
