---
creation_rules:
  - path_regex: ^docker/c0/[^/]+/encrypted/.*$
    key_groups:
      - age:
          - age1klqk5f49ha4yyg5ehs34nkvef4pax29yvtvch4j3g5ruext0k9jqvdpdw2
          - age176gqr8lshvtzyjpn73696rm4a4jh8cevsvk3ccqtnqr5q3f8wdfqwvztpn
          - age14rz62knn67euvge6k7267dcuclrxlecps54hdgjatpf23vgwx55qzl3tcy
  - path_regex: ^encrypted/.*[.]env$
    key_groups:
      - age:
          - age1klqk5f49ha4yyg5ehs34nkvef4pax29yvtvch4j3g5ruext0k9jqvdpdw2
          - age176gqr8lshvtzyjpn73696rm4a4jh8cevsvk3ccqtnqr5q3f8wdfqwvztpn
          - age14rz62knn67euvge6k7267dcuclrxlecps54hdgjatpf23vgwx55qzl3tcy
