---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: llmkube
  namespace: flux-system
spec:
  interval: 1h
  url: https://defilantech.github.io/LLMKube
