---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/flux/helmrelease-defaults
resources:
  - ../../apps/default
  - ../../apps/kube-system/cilium/config/ks.yaml
  - ../../apps/networking/envoy-gateway/config/ks.yaml
  - ../../apps/rook-ceph/rook-ceph/config/ks.yaml
  - ../../apps/kopiur-system/kopiur/config/ks.yaml
  - ../../apps/database/postgres/config/ks.yaml
  - ../../apps/database/dragonfly/config/ks.yaml
  - ../../apps/observability/silence-operator/config/ks.yaml
  - ../../apps/system-upgrade/tuppr/config/ks.yaml
  - ../../apps/flux-system/image-automation/ks.yaml
  - ../../apps/external-secrets/openbao-config/ks.yaml
