---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-automation-forgejo
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: image-automation-forgejo
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        identity: "{{ .identity }}"
        known_hosts: "{{ .known_hosts }}"
  data:
    - secretKey: identity
      remoteRef:
        key: platform/kubernetes/flux-system/image-automation
        property: identity
    - secretKey: known_hosts
      remoteRef:
        key: platform/kubernetes/flux-system/image-automation
        property: known_hosts
