---
junos_intent_operation: check
junos_intent_commit_comment: "Ansible intent deployment"
junos_intent_candidate_path: "{{ lookup('ansible.builtin.env', 'JUNOS_CANDIDATE_FILE') }}"
junos_intent_diff_path: "{{ playbook_dir }}/../.build/{{ inventory_hostname }}.diff"
