---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-database
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target:
    name: keycloak-database
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: keycloak_a
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef: { key: platform/kubernetes/database/cloudnative-pg, property: keycloak_a_password }
