---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-tsig
spec:
  refreshInterval: 15m
  refreshPolicy: Periodic
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target:
    name: external-dns-tsig
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        tsig-secret: "{{ .tsig_secret }}"
  data:
    - secretKey: tsig_secret
      remoteRef:
        key: platform/kubernetes/networking/external-dns
        property: tsig_secret
        conversionStrategy: Default
        decodingStrategy: None
