---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
    namespace: flux-system
  interval: 1h
  values:
    replicaCount: 2
    serviceAccount:
      create: true
      automount: true
    talosServiceAccount:
      create: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
      seccompProfile: { type: RuntimeDefault }
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: { drop: [ALL] }
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: tuppr
            topologyKey: kubernetes.io/hostname
    monitoring:
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          matchLabels:
            dashboards: grafana
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true
