---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-r2
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: kopiur-r2-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        R2_BUCKET: "{{ .R2_BUCKET }}"
        R2_ENDPOINT: "{{ .R2_ENDPOINT }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: platform/kubernetes/kopiur-system/r2
