---
routing:
  router_id: { topology: bgp.router_id }
  autonomous_system: { topology: bgp.local_as }
  static_routes:
    - { route: { topology: bgp.lb_pool }, action: discard }
  instances:
    - name: VR-XLSATU
      type: virtual-router
      interfaces: [ge-0/0/0.0, irb.2512]
  policies:
    - name: IMPORT-HOME-INTO-MASTER
      terms:
        - { name: HOME, from_instance: VR-XLSATU, route_filter: { topology: networks.home.subnet }, action: accept }
        - { name: REJECT-REST, action: reject }
    - name: IMPORT-MASTER-INTERNAL-INTO-HOME
      terms:
        - { name: MGMT, from_instance: master, route_filter: { topology: networks.mgmt.subnet }, action: accept }
        - { name: PROD, from_instance: master, route_filter: { topology: networks.prod.subnet }, action: accept }
        - { name: DEV, from_instance: master, route_filter: { topology: networks.dev.subnet }, action: accept }
        - { name: EDGE, from_instance: master, route_filter: { topology: networks.edge.subnet }, action: accept }
        - { name: REJECT-REST, action: reject }
    - name: IMPORT-CILIUM-LB
      terms:
        - name: CILIUM-LB-HOSTS
          from_protocol: bgp
          route_filter:
            prefix: { topology: bgp.lb_pool }
            prefix_length_range: /32-/32
          action: accept
        - { name: REJECT-REST, action: reject }
    - name: EXPORT-CILIUM-NONE
      terms:
        - { name: REJECT-ALL, action: reject }
    - name: LOAD-BALANCE-CILIUM
      terms:
        - { name: CILIUM, from_protocol: bgp, load_balance: per-packet }
        - { name: ACCEPT-REST, action: accept }
  instance_imports:
    - { routing_instance: master, policy: IMPORT-HOME-INTO-MASTER }
    - { routing_instance: VR-XLSATU, policy: IMPORT-MASTER-INTERNAL-INTO-HOME }
  forwarding_table_export: LOAD-BALANCE-CILIUM
  bgp:
    name: CILIUM
    type: external
    local_address: { topology: bgp.local_address }
    local_as: { topology: bgp.local_as }
    peer_as: { topology: bgp.peer_as }
    authentication_keys: { topology: bgp.authentication_keys }
    hold_time: 9
    multipath: true
    import_policy: IMPORT-CILIUM-LB
    export_policy: EXPORT-CILIUM-NONE
    family: inet
    unicast:
      prefix_limit: { maximum: 128, teardown: 100, idle_timeout: 5 }
    neighbors: { topology: bgp.peers }
  protocols:
    - [l2-learning, global-mode, switching]
  rstp:
    bridge_priority: 8k
    interfaces:
      - { name: ge-0/0/6, mode: point-to-point }
      - { name: ge-0/0/14, mode: point-to-point }
      - { name: ge-0/0/15, mode: point-to-point }
      - { name: xe-0/0/18, mode: point-to-point }
      - { name: xe-0/0/19, mode: point-to-point }
