---
system:
  hostname: srx1500
  domain: { topology: system.domain }
  timezone: Asia/Jakarta
  services:
    - [netconf, ssh]
    - [ssh, protocol-version, v2]
    - [ssh, max-sessions-per-connection, 5]
    - [ssh, client-alive-count-max, 3]
    - [ssh, client-alive-interval, 10]
    - [ssh, connection-limit, 10]
    - [ssh, rate-limit, 5]
    - [web-management, https, interface, irb.2510]
    - [web-management, https, system-generated-certificate]
  name_servers:
    - { topology: dns.primary }
    - { topology: dns.secondary }
  ntp_servers:
    - address: { topology: ntp.preferred }
      prefer: true
    - address: { topology: ntp.secondary }
  syslog:
    - [archive, size, 10m]
    - [archive, files, 10]
    - [user, "*", any, emergency]
    - [file, interactive-commands, interactive-commands, any]
    - [file, messages, any, notice]
    - [file, messages, authorization, info]
    - [file, security-log, any, any]
    - [file, security-log, match, "RT_FLOW|RT_SCREEN"]
  options:
    - [max-configurations-on-flash, 5]
    - [internet-options, no-source-quench]
    - [internet-options, tcp-drop-synfin-set]
    - [internet-options, no-tcp-reset, drop-all-tcp]
    - [license, autoupdate, url, "https://ae1.juniper.net/junos/key_retrieval"]
    - [services, ssh, macs, hmac-sha2-256]
    - [services, ssh, macs, hmac-sha2-512]
