---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: flux-system
  interval: 1h
  values:
    crds:
      enabled: true
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/component: controller
    webhook:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: cert-manager
              app.kubernetes.io/component: webhook
    cainjector:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: cert-manager
              app.kubernetes.io/component: cainjector
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
