---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-auth
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target:
    name: snmp-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        SNMP_USERNAME: "{{ .username }}"
        SNMP_AUTH_PASSWORD: "{{ .auth_password }}"
        SNMP_PRIV_PASSWORD: "{{ .priv_password }}"
        auth.yml: |-
          auths:
            infrastructure_v3:
              version: 3
              security_level: authPriv
              username: ${SNMP_USERNAME}
              password: ${SNMP_AUTH_PASSWORD}
              auth_protocol: SHA
              priv_protocol: AES
              priv_password: ${SNMP_PRIV_PASSWORD}
  dataFrom:
    - extract: { key: platform/kubernetes/observability/snmp }
