---
dhcp:
  pools:
    - name: MGMT
      network: { topology: networks.mgmt.subnet }
      range: { low: { topology: networks.mgmt.dhcp_low }, high: { topology: networks.mgmt.dhcp_high } }
      router: { topology: networks.mgmt.gateway }
      dns: [{ topology: dns.internal }]
      reservations: { topology: reservations.mgmt }
    - name: PROD
      network: { topology: networks.prod.subnet }
      range: { low: { topology: networks.prod.dhcp_low }, high: { topology: networks.prod.dhcp_high } }
      router: { topology: networks.prod.gateway }
      dns: [{ topology: dns.internal }]
      reservations: { topology: reservations.prod }
    - name: DEV
      network: { topology: networks.dev.subnet }
      range: { low: { topology: networks.dev.dhcp_low }, high: { topology: networks.dev.dhcp_high } }
      router: { topology: networks.dev.gateway }
      dns: [{ topology: dns.internal }]
      reservations: { topology: reservations.dev }
  groups:
    - { name: MGMT, interface: irb.2510, pool: MGMT }
    - { name: PROD, interface: irb.2511, pool: PROD }
    - { name: DEV, interface: irb.2513, pool: DEV }

