---
nat:
  source_rules:
    - name: HOME-TO-PRIMARY
      from_zone: HOME
      to_zone: WAN-PRIMARY
      rules:
        - name: HOME-SNAT
          source: { topology: networks.home.subnet }
          destination: 0.0.0.0/0
          action: interface
    - name: INTERNAL-TO-SECONDARY
      from_zone: [MGMT, PROD, DEV]
      to_zone: WAN-SECONDARY
      rules:
        - name: INTERNAL-SNAT
          source: 0.0.0.0/0
          destination: 0.0.0.0/0
          action: interface

