---
routing:
  instances:
    - name: VR-PRIMARY
      type: virtual-router
      interfaces: [ge-0/0/0.0, irb.2512]
  policies:
    - name: IMPORT-HOME-INTO-MASTER
      terms:
        - { name: HOME, from_instance: VR-PRIMARY, action: accept }
        - { name: REJECT-REST, action: reject }
    - name: IMPORT-MASTER-INTERNAL-INTO-HOME
      terms:
        - { name: MGMT, route_filter: { topology: networks.mgmt.subnet }, action: accept }
        - { name: PROD, route_filter: { topology: networks.prod.subnet }, action: accept }
        - { name: DEV, route_filter: { topology: networks.dev.subnet }, action: accept }
        - { name: REJECT-REST, action: reject }
  instance_imports: [IMPORT-HOME-INTO-MASTER]
  rstp_interfaces: [ge-0/0/6, xe-0/0/18, xe-0/0/19]

