[Unit]
RequiresMountsFor=/srv/containers
After=srv-containers.mount

[Service]
ExecStartPre=/usr/local/sbin/assert-c1-mount containers /srv/containers
ExecStart=
ExecStart=/usr/bin/containerd --config /etc/containerd/config.toml --root /srv/containers/containerd
