---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumbgpclusterconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-srx1500
spec:
  nodeSelector:
    matchLabels:
      bgp.monosense.io/enabled: "true"
  bgpInstances:
    - name: cilium-srx1500
      localASN: 64513
      peers:
        - name: srx1500
          peerASN: 64512
          peerAddress: 10.25.11.1
          peerConfigRef:
            name: cilium-srx1500
