---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-bgp-auth-bsd-k8s-01
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target: { name: cilium-bgp-auth-bsd-k8s-01, creationPolicy: Owner, deletionPolicy: Retain }
  data:
    - { secretKey: password, remoteRef: { key: platform/kubernetes/kube-system/cilium-bgp-bsd-k8s-01, property: password } }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-bgp-auth-bsd-k8s-02
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target: { name: cilium-bgp-auth-bsd-k8s-02, creationPolicy: Owner, deletionPolicy: Retain }
  data:
    - { secretKey: password, remoteRef: { key: platform/kubernetes/kube-system/cilium-bgp-bsd-k8s-02, property: password } }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-bgp-auth-bsd-k8s-03
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target: { name: cilium-bgp-auth-bsd-k8s-03, creationPolicy: Owner, deletionPolicy: Retain }
  data:
    - { secretKey: password, remoteRef: { key: platform/kubernetes/kube-system/cilium-bgp-bsd-k8s-03, property: password } }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-bgp-auth-bsd-k8s-04
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target: { name: cilium-bgp-auth-bsd-k8s-04, creationPolicy: Owner, deletionPolicy: Retain }
  data:
    - { secretKey: password, remoteRef: { key: platform/kubernetes/kube-system/cilium-bgp-bsd-k8s-04, property: password } }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-bgp-auth-bsd-k8s-05
spec:
  refreshPolicy: Periodic
  refreshInterval: 15m
  secretStoreRef: { kind: ClusterSecretStore, name: openbao }
  target: { name: cilium-bgp-auth-bsd-k8s-05, creationPolicy: Owner, deletionPolicy: Retain }
  data:
    - { secretKey: password, remoteRef: { key: platform/kubernetes/kube-system/cilium-bgp-bsd-k8s-05, property: password } }
