---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-srx1500-bsd-k8s-01
spec:
  authSecretRef: cilium-bgp-auth-bsd-k8s-01
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: false
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.monosense.io/advertisement: loadbalancer-hosts
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-srx1500-bsd-k8s-02
spec:
  authSecretRef: cilium-bgp-auth-bsd-k8s-02
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: false
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.monosense.io/advertisement: loadbalancer-hosts
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-srx1500-bsd-k8s-03
spec:
  authSecretRef: cilium-bgp-auth-bsd-k8s-03
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: false
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.monosense.io/advertisement: loadbalancer-hosts
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-srx1500-bsd-k8s-04
spec:
  authSecretRef: cilium-bgp-auth-bsd-k8s-04
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: false
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.monosense.io/advertisement: loadbalancer-hosts
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-srx1500-bsd-k8s-05
spec:
  authSecretRef: cilium-bgp-auth-bsd-k8s-05
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: false
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.monosense.io/advertisement: loadbalancer-hosts
