---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumbgppeerconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-srx1500
spec:
  authSecretRef: cilium-bgp-auth
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: false
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.monosense.io/advertisement: loadbalancer-hosts
