---
apiVersion: v1
kind: Service
metadata:
  name: kube-vip
  labels:
    bgp.monosense.io/advertise: "true"
    lbipam.monosense.io/class: infrastructure
  annotations:
    lbipam.cilium.io/ips: 10.25.20.10
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - port: 6443
